Fix check_license.yml.
It was still broken.

diff --git a/.github/workflows/check_license.yml b/.github/workflows/check_license.yml
--- a/.github/workflows/check_license.yml
+++ b/.github/workflows/check_license.yml
@@ -2,27 +2,35 @@
 name: Check license
 
 on:
-  pull_request:
-    branches:
-      - main
+  push:
 
 jobs:
-  test_license:
+  check_license:
     name: Check license headers
+
+    runs-on: ubuntu-latest
+
     steps:
     - uses: actions/checkout@v2
+      with:
+        fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
 
     - name: Get changed files
       id: changed-files
       uses: tj-actions/changed-files@v1.1.2
 
     - name: Check copyright header in added files
-    - shell: bash
-    - run: |
+      shell: bash
+      run: |
         missing=0
+        if [ -z "${{ steps.changed-files.outputs.added_files }}" ]; then
+          exit 0
+        fi
         for file in "${{ steps.changed-files.outputs.added_files }}"; do
-          if ! egrep -q '(Facebook, Inc(\.|,)? and its affiliates)|([0-9]{4}-present(\.|,)? Facebook)|([0-9]{4}(\.|,)? Facebook)' $file
-          echo "Missing copyright header in $file"
-          missing=$(expr $missing + 1)
+          echo "$file was modified"
+          if ! egrep -q '(Facebook, Inc(\.|,)? and its affiliates)|([0-9]{4}-present(\.|,)? Facebook)|([0-9]{4}(\.|,)? Facebook)' $file; then
+            echo "Missing copyright header in $file"
+            missing=$(expr $missing + 1)
+          fi
         done
         exit $missing
